In [7]:
# Import Dependencies

import geopandas as gpd
import pandas as pd
from sqlalchemy import create_engine
from rapidfuzz import process, fuzz

In [8]:
# Create a PostgreSQL connection
engine = create_engine("postgresql://postgres:p00ls!dE@localhost:5432/Toronto_OpenData")

# Read the GeoJSON file containing intersection geometries
intersection_gdf = gpd.read_file(r'C:\Users\rahul\OneDrive\Desktop\Data Analyst\Projects\OpenData\map_files\centreline-intersection-4326.geojson')

# Read the CSV file containing matched Toronto intersections with 311 service request data
intersections = pd.read_sql_query("SELECT * FROM intersection_top100", engine)

c:\Users\rahul\OneDrive\Desktop\Data Analyst\Projects\Clipboard Sales Project\.conda\Lib\site-packages\geopandas\io\file.py:576: UserWarning: Error parsing datetimes, original strings are returned: Out of bounds nanosecond timestamp: 3000-01-01T00:00:00, at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
  return pyogrio.read_dataframe(path_or_bytes, bbox=bbox, **kwargs)

In [16]:
intersections.head()

,service_request_type,year,ward_id,ward,intersection_street_1,intersection_street_2,yearly_requests
0,Amplified Or Musical Instrument Noise,2022,10,Spadina-Fort York,Queen St W,Spadina Ave,111
1,Traffic Signal Repair,2021,14,Toronto-Danforth,Pape Ave,Danforth Ave,51
2,Road Pothole / Road Damage,2026,16,Don Valley East,Don Mills Rd,Overlea Blvd,47
3,Road Pothole / Road Damage,2026,6,York Centre,Steeles Ave W,Keele St,46
4,Road Pothole / Road Damage,2025,23,Scarborough North,Sheppard Ave E,McCowan Rd,46

In [17]:
# Handle missing values in the intersection street columns by filling them with empty strings
intersections['intersection_street_1'] = intersections['intersection_street_1'].fillna('')
intersections['intersection_street_2'] = intersections['intersection_street_2'].fillna('')

intersections['intersection_street_1'] = intersections['intersection_street_1'].str.replace('F G', '', regex=False).str.replace('Gardiner X Y', 'Gardiner XWY', regex=False).str.replace("Sewell's", "Sewells", regex=False)
intersections['intersection_street_2'] = intersections['intersection_street_2'].str.replace('F G', '', regex=False).str.replace('Gardiner X Y', 'Gardiner XWY', regex=False).str.replace("Sewell's", "Sewells", regex=False)


# create a column for intersection description matching the format in the intersection GeoJSON file
intersections['intersection_description'] = intersections['intersection_street_1'] + ' / ' + intersections['intersection_street_2']

In [18]:
# Clean Geomtery column
 
instersection_gdf = intersection_gdf[['INTERSECTION_DESC','geometry']]

intersection_gdf['Longitude'] = intersection_gdf.explode('geometry').geometry.x
intersection_gdf['Latitude'] = intersection_gdf.explode('geometry').geometry.y

intersection_gdf.drop(columns=['geometry'], inplace=True)
intersection_gdf

,_id,INTERSECTION_ID,DATE_EFFECTIVE,DATE_EXPIRY,ELEVATION_ID,INTERSECTION_DESC,CLASSIFICATION,CLASSIFICATION_DESC,NUMBER_OF_ELEVATIONS,ELEVATION_FEATURE_CODE,...,ELEVATION,ELEVATION_UNIT,HEIGHT_RESTRICTION,HEIGHT_RESTRICTION_UNIT,STATE,TRANS_ID_CREATE,TRANS_ID_EXPIRE,OBJECTID,Longitude,Latitude
0,1,13470264,2008-12-11 23:22:46,3000-01-01T00:00:00,13,Robindale Ave / Rimilton Ave,MNRSL,Minor-Single Level,1,501300.0,...,None,None,None,None,8,200000,-1,1,-79.531070,43.607243
1,2,13470193,2008-12-11 23:22:46,3000-01-01T00:00:00,4718,Bellman Ave / Valermo Dr,MNRSL,Minor-Single Level,1,501300.0,...,None,None,None,None,8,200000,-1,4,-79.531373,43.609600
2,3,13470188,2008-12-11 23:22:46,3000-01-01T00:00:00,32728,Rimilton Ave / Valermo Dr,SEUSL,Pseudo Intersection-Single Level,1,509200.0,...,None,None,None,None,8,200000,-1,5,-79.530118,43.609829
3,4,13470203,2008-12-11 23:22:46,3000-01-01T00:00:00,21669,Valermo Dr / Goa Crt,MNRSL,Minor-Single Level,1,501300.0,...,None,None,None,None,8,200000,-1,7,-79.533175,43.609190
4,5,13469995,2008-12-11 23:22:46,3000-01-01T00:00:00,32744,Fordhouse Blvd / Algie Ave,MNRSL,Minor-Single Level,1,501300.0,...,None,None,None,None,8,200000,-1,16,-79.535987,43.616387
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46822,46823,60053985,2026-02-10 09:07:37,3000-01-01T00:00:00,60053986,Martin Grove Rd / Westgrove Park Trl,LSRSL,Lesser-Single Level,1,504000.0,...,None,None,None,None,8,60071989,-1,129829,-79.566269,43.681398
46823,46824,60054017,2026-02-10 09:04:47,3000-01-01T00:00:00,60054018,Westgrove Park Trl,CDSSL,Cul de Sac-Single Level,1,509100.0,...,None,None,None,None,8,60071988,-1,129830,-79.567096,43.681472
46824,46825,60054006,2026-02-10 09:04:47,3000-01-01T00:00:00,60054007,Westgrove Park Trl,LSRSL,Lesser-Single Level,1,504000.0,...,None,None,None,None,8,60071988,-1,129831,-79.567094,43.681552
46825,46826,60054395,2026-02-12 13:08:56,3000-01-01T00:00:00,60054396,Humber River Recreational Trl,LSRSL,Lesser-Single Level,1,504000.0,...,None,None,None,None,8,60072348,-1,129832,-79.503212,43.661758
46826,46827,60054376,2026-02-12 13:09:59,3000-01-01T00:00:00,60054377,Humber River Recreational Trl,LSRSL,Lesser-Single Level,1,504000.0,...,None,None,None,None,8,60072349,-1,129833,-79.502833,43.661552

In [19]:
# Function to normalize strings and return a set of tokens

import re

def normalize(s):
    if not s:
        return ""
    
    tokens = re.split(r"[,/]", s.lower())
    tokens = [t.strip() for t in tokens if t.strip() not in ("", "/")]
    
    # sort so order doesn't matter
    tokens = sorted(tokens)
    
    return " ".join(tokens)

In [20]:
# Apply normalization to both datasets
intersection_gdf['normalized_desc'] = intersection_gdf['INTERSECTION_DESC'].apply(normalize)
intersections['normalized_desc'] = intersections['intersection_description'].apply(normalize)

# Merge datasets on the normalized intersection description
directmatch_gdf = intersection_gdf.merge(intersections, on='normalized_desc', how='inner')

# Trim the direct matches dataset
directmatch_gdf = directmatch_gdf[['INTERSECTION_DESC', 'ward', 'intersection_street_1', 'intersection_street_2', 'service_request_type', 'normalized_desc','yearly_requests','Latitude','Longitude']]
directmatch_gdf

,INTERSECTION_DESC,ward,intersection_street_1,intersection_street_2,service_request_type,normalized_desc,yearly_requests,Latitude,Longitude
0,Robindale Ave / Rimilton Ave,Etobicoke-Lakeshore,Rimilton Ave,Robindale Ave,Injured Wildlife,rimilton ave robindale ave,1,43.607243,-79.531070
1,Bellman Ave / Valermo Dr,Etobicoke-Lakeshore,Bellman Ave,Valermo Dr,Clean Up Illegal Dumping On City Road Allowance,bellman ave valermo dr,1,43.609600,-79.531373
2,Bellman Ave / Valermo Dr,Etobicoke-Lakeshore,Bellman Ave,Valermo Dr,Amplified Or Musical Instrument Noise,bellman ave valermo dr,1,43.609600,-79.531373
3,Bellman Ave / Valermo Dr,Etobicoke-Lakeshore,Bellman Ave,Valermo Dr,Missing / Damaged Street Or Traffic Signs,bellman ave valermo dr,1,43.609600,-79.531373
4,Bellman Ave / Valermo Dr,Etobicoke-Lakeshore,Bellman Ave,Valermo Dr,Missing / Damaged Street Or Traffic Signs,bellman ave valermo dr,1,43.609600,-79.531373
...,...,...,...,...,...,...,...,...,...
149140,Humber River Recreational Trl,Parkdale-High Park,Humber River Recreational Trl,,Injured Wildlife,humber river recreational trl,1,43.661552,-79.502833
149141,Humber River Recreational Trl,Etobicoke Centre,Humber River Recreational Trl,,Clean Up Debris On Road,humber river recreational trl,1,43.661552,-79.502833
149142,Humber River Recreational Trl,Etobicoke Centre,Humber River Recreational Trl,,Park Use,humber river recreational trl,1,43.661552,-79.502833
149143,Humber River Recreational Trl,Parkdale-High Park,Humber River Recreational Trl,,Tree Emergency Clean Up,humber river recreational trl,1,43.661552,-79.502833
149144,Humber River Recreational Trl,Parkdale-High Park,Humber River Recreational Trl,,Tree Emergency Clean Up,humber river recreational trl,1,43.661552,-79.502833

In [21]:
# Obtain unmatched intersections

unmatched_intersections = intersections[~intersections['normalized_desc'].isin(directmatch_gdf['normalized_desc'])]
unmatched_intersections_unique = unmatched_intersections.groupby(['intersection_description','normalized_desc','intersection_street_1','intersection_street_2','ward',]).size().reset_index(name='count').sort_values(by='count', ascending=False)

unmatched_intersections

,service_request_type,year,ward_id,ward,intersection_street_1,intersection_street_2,yearly_requests,intersection_description,normalized_desc
2,Road Pothole / Road Damage,2026,16,Don Valley East,Don Mills Rd,Overlea Blvd,47,Don Mills Rd / Overlea Blvd,don mills rd overlea blvd
5,Road Pothole / Road Damage,2026,7,Humber River-Black Creek,Steeles Ave W,Jane St,46,Steeles Ave W / Jane St,jane st steeles ave w
11,Road Pothole / Road Damage,2026,22,Scarborough-Agincourt,Warden Av S 401 C W Ramp,Arkona Dr,35,Warden Av S 401 C W Ramp / Arkona Dr,arkona dr warden av s 401 c w ramp
13,Traffic Signal Repair,2025,16,Don Valley East,Eglinton Ave E,Bermondsey Rd,32,Eglinton Ave E / Bermondsey Rd,bermondsey rd eglinton ave e
16,Road Pothole / Road Damage,2022,14,Toronto-Danforth,Don Valley Parkway N,Don Valley Parkway S,31,Don Valley Parkway N / Don Valley Parkway S,don valley parkway n don valley parkway s
...,...,...,...,...,...,...,...,...,...
165338,Tree Emergency Clean Up,2024,10,Spadina-Fort York,Martin Goodman Trl,Queens Quay W,1,Martin Goodman Trl / Queens Quay W,martin goodman trl queens quay w
165344,Tree Emergency Clean Up,2024,11,University-Rosedale,Aylmer Ave,Rosedale Valley Rd,1,Aylmer Ave / Rosedale Valley Rd,aylmer ave rosedale valley rd
165347,Tree Emergency Clean Up,2024,11,University-Rosedale,Barton Ave,Pendrith Lane,1,Barton Ave / Pendrith Lane,barton ave pendrith lane
165356,Tree Emergency Clean Up,2024,11,University-Rosedale,Don Valley Brick Works Trl,Bayview Multi-Use Trail,1,Don Valley Brick Works Trl / Bayview Multi-Use...,bayview multi-use trail don valley brick works...
165369,Tree Emergency Clean Up,2024,11,University-Rosedale,Willowvale Lane,Christie Pits Trl,1,Willowvale Lane / Christie Pits Trl,christie pits trl willowvale lane

In [22]:
def fuzzy_match(df1_unmatched, df2_unmatched, threshold=90):
    results = []
    
    choices = df2_unmatched["normalized_desc"].tolist()
    
    for idx, val in df1_unmatched["normalized_desc"].items():
        match, score, match_idx = process.extractOne(
            val, choices, scorer=fuzz.token_sort_ratio
        )
        
        if score >= threshold:
            results.append({
                'INTERSECTION_DESC': df2_unmatched.loc[match_idx, 'INTERSECTION_DESC'],
                "intersection_street_1": df1_unmatched.loc[idx, 'intersection_street_1'],
                "intersection_street_2": df1_unmatched.loc[idx, 'intersection_street_2'],
                'ward': df1_unmatched.loc[idx, 'ward'],
                'Latitude':df2_unmatched.loc[match_idx, 'Latitude'],
                "Longitude":df2_unmatched.loc[match_idx,'Longitude'],
                "score": score
            })
    
    return results

fuzzy_matches = fuzzy_match(unmatched_intersections_unique, intersection_gdf, threshold=90)

In [23]:
# Save meatches as dataframe

fuzzy_df = pd.DataFrame(fuzzy_matches)
fuzzy_df

,INTERSECTION_DESC,intersection_street_1,intersection_street_2,ward,Latitude,Longitude,score
0,Humber River Recreational Trl / Humber River,Humber River Trl,Humber River Recreational Trl,Etobicoke Centre,43.723644,-79.540723,95.454545
1,Spadina Ave / Spadina Cres,Spadina Ave,Spadina Rd,University-Rosedale,43.660368,-79.401029,91.304348
2,York St / Queens Quay W,Queens Quay W,York St,Spadina-Fort York,43.640028,-79.380037,100.000000
3,Royal York S Dundas E Ramp / Dundas E Royal Yo...,Royal York S Dundas E Ramp,Royal York N Dundas W Ramp,Etobicoke-Lakeshore,43.657597,-79.516662,96.226415
4,Lake Shore Blvd W / Gardiner Jameson Av Ramp,Jameson Av Gardiner W Ramp,Lake Shore Blvd W,Parkdale-High Park,43.633468,-79.436362,97.674419
...,...,...,...,...,...,...,...
393,Overton Cres / The Donway W,Overton Cres,The Donway W,Don Valley East,43.740753,-79.345154,100.000000
394,Highway 427 / Eglinton Ave West Trl,Highway 427 S,Eglinton Ave West Trl,Etobicoke Centre,43.670949,-79.574950,97.058824
395,Highway 427 / Renforth Dr,Highway 427 N,Renforth Dr,Etobicoke North,43.676652,-79.592178,95.833333
396,Princes' Blvd / Prince Edward Island Cres,Prince Edward Island Cres,Princes Blvd,Spadina-Fort York,43.632021,-79.422261,98.701299
397,McCowan Rd / 401 C W Mccowan Rd Ramp / Mccowan...,Mccowan Rd S 401 C W Ramp,401 C W Mccowan Rd N Ramp,Scarborough North,43.782876,-79.255514,91.891892

In [24]:
unmatched_intersections

,service_request_type,year,ward_id,ward,intersection_street_1,intersection_street_2,yearly_requests,intersection_description,normalized_desc
2,Road Pothole / Road Damage,2026,16,Don Valley East,Don Mills Rd,Overlea Blvd,47,Don Mills Rd / Overlea Blvd,don mills rd overlea blvd
5,Road Pothole / Road Damage,2026,7,Humber River-Black Creek,Steeles Ave W,Jane St,46,Steeles Ave W / Jane St,jane st steeles ave w
11,Road Pothole / Road Damage,2026,22,Scarborough-Agincourt,Warden Av S 401 C W Ramp,Arkona Dr,35,Warden Av S 401 C W Ramp / Arkona Dr,arkona dr warden av s 401 c w ramp
13,Traffic Signal Repair,2025,16,Don Valley East,Eglinton Ave E,Bermondsey Rd,32,Eglinton Ave E / Bermondsey Rd,bermondsey rd eglinton ave e
16,Road Pothole / Road Damage,2022,14,Toronto-Danforth,Don Valley Parkway N,Don Valley Parkway S,31,Don Valley Parkway N / Don Valley Parkway S,don valley parkway n don valley parkway s
...,...,...,...,...,...,...,...,...,...
165338,Tree Emergency Clean Up,2024,10,Spadina-Fort York,Martin Goodman Trl,Queens Quay W,1,Martin Goodman Trl / Queens Quay W,martin goodman trl queens quay w
165344,Tree Emergency Clean Up,2024,11,University-Rosedale,Aylmer Ave,Rosedale Valley Rd,1,Aylmer Ave / Rosedale Valley Rd,aylmer ave rosedale valley rd
165347,Tree Emergency Clean Up,2024,11,University-Rosedale,Barton Ave,Pendrith Lane,1,Barton Ave / Pendrith Lane,barton ave pendrith lane
165356,Tree Emergency Clean Up,2024,11,University-Rosedale,Don Valley Brick Works Trl,Bayview Multi-Use Trail,1,Don Valley Brick Works Trl / Bayview Multi-Use...,bayview multi-use trail don valley brick works...
165369,Tree Emergency Clean Up,2024,11,University-Rosedale,Willowvale Lane,Christie Pits Trl,1,Willowvale Lane / Christie Pits Trl,christie pits trl willowvale lane

In [25]:
fuzzy_matches_df = fuzzy_df.merge(unmatched_intersections, on = ['intersection_street_1','intersection_street_2','ward'],how = 'inner')

fuzzy_matches_df.drop(columns = ['intersection_description','score'], inplace = True)

In [26]:
fuzzy_matches_df

,INTERSECTION_DESC,intersection_street_1,intersection_street_2,ward,Latitude,Longitude,service_request_type,year,ward_id,yearly_requests,normalized_desc
0,Humber River Recreational Trl / Humber River,Humber River Trl,Humber River Recreational Trl,Etobicoke Centre,43.723644,-79.540723,Traffic Signal Repair,2020,2,13,humber river recreational trl humber river trl
1,Humber River Recreational Trl / Humber River,Humber River Trl,Humber River Recreational Trl,Etobicoke Centre,43.723644,-79.540723,Road Pothole / Road Damage,2020,2,9,humber river recreational trl humber river trl
2,Humber River Recreational Trl / Humber River,Humber River Trl,Humber River Recreational Trl,Etobicoke Centre,43.723644,-79.540723,Traffic Signal Repair,2023,2,9,humber river recreational trl humber river trl
3,Humber River Recreational Trl / Humber River,Humber River Trl,Humber River Recreational Trl,Etobicoke Centre,43.723644,-79.540723,Traffic Signal Repair,2021,2,9,humber river recreational trl humber river trl
4,Humber River Recreational Trl / Humber River,Humber River Trl,Humber River Recreational Trl,Etobicoke Centre,43.723644,-79.540723,Pick Up Dead Wildlife,2022,2,7,humber river recreational trl humber river trl
...,...,...,...,...,...,...,...,...,...,...,...
4173,Overton Cres / The Donway W,Overton Cres,The Donway W,Don Valley East,43.740753,-79.345154,Road Pothole / Road Damage,2021,16,1,overton cres the donway w
4174,Highway 427 / Eglinton Ave West Trl,Highway 427 S,Eglinton Ave West Trl,Etobicoke Centre,43.670949,-79.574950,Road Plowing Request,2026,2,1,eglinton ave west trl highway 427 s
4175,Highway 427 / Renforth Dr,Highway 427 N,Renforth Dr,Etobicoke North,43.676652,-79.592178,Injured Wildlife,2021,1,1,highway 427 n renforth dr
4176,Princes' Blvd / Prince Edward Island Cres,Prince Edward Island Cres,Princes Blvd,Spadina-Fort York,43.632021,-79.422261,Watermain-Possible Break,2020,10,1,prince edward island cres princes blvd
4177,McCowan Rd / 401 C W Mccowan Rd Ramp / Mccowan...,Mccowan Rd S 401 C W Ramp,401 C W Mccowan Rd N Ramp,Scarborough North,43.782876,-79.255514,Traffic Signal Repair,2026,23,1,401 c w mccowan rd n ramp mccowan rd s 401 c w...

In [27]:
fuzzy_matches_group = (
    fuzzy_matches_df
    .groupby([
        'INTERSECTION_DESC',
        'ward',
        'year',
        'service_request_type',
        'section'
    ], as_index=False)
    .agg({
        'yearly_requests': 'sum',
        'Latitude': 'first',
        'Longitude': 'first' 
    })
)

direct_matches_group = (
    directmatch_gdf
    .groupby([
        'INTERSECTION_DESC',
        'ward',
        'year',
        'service_request_type',
        'section'
    ], as_index=False)
    .agg({
        'yearly_requests': 'sum',
        'Latitude': 'first',
        'Longitude': 'first' 
    })
)

KeyError: 'section'

In [ ]:
fuzzy_matches_group.sort_values('yearly_requests',ascending=False).head(50)

,INTERSECTION_DESC,ward,year,service_request_type,section,yearly_requests,Latitude,Longitude
768,Gardiner Lakeshore E / Gardiner E Lower Jarvis...,Spadina-Fort York,2024,Contractor Complaint,Road Operations,25,43.645324,-79.371020
4104,York St / Queens Quay W,Spadina-Fort York,2025,Traffic Signal Repair,TMC,20,43.640028,-79.380037
3750,Spadina Ave / Spadina Cres,University-Rosedale,2025,Traffic Signal Repair,TMC,19,43.660368,-79.401029
781,Gardiner Lakeshore E / Gardiner E Lower Jarvis...,Spadina-Fort York,2025,Contractor Complaint,Road Operations,19,43.645324,-79.371020
3493,Robertson Cres / Queens Quay W,Spadina-Fort York,2025,Traffic Signal Repair,TMC,18,43.639029,-79.385463
755,Gardiner Lakeshore E / Gardiner E Lower Jarvis...,Spadina-Fort York,2023,Contractor Complaint,Road Operations,18,43.645324,-79.371020
747,Gardiner Lakeshore E / Gardiner E Lower Jarvis...,Spadina-Fort York,2022,Road Pothole / Road Damage,Road Operations,17,43.645324,-79.371020
4077,York St / Queens Quay W,Spadina-Fort York,2023,Traffic Signal Repair,TMC,17,43.640028,-79.380037
855,Gardiner X W Gardiner C W / Gardiner XWY,Etobicoke-Lakeshore,2022,Clean Up Debris On Road,Road Operations,17,43.620141,-79.515076
2196,Highway 401 / Warden Ave,Scarborough Centre,2026,Road Pothole / Road Damage,Road Operations,16,43.770475,-79.304113
3573,Royal York S Dundas E Ramp / Dundas E Royal Yo...,Etobicoke-Lakeshore,2026,Road Pothole / Road Damage,Road Operations,15,43.657597,-79.516662
3556,Royal York S Dundas E Ramp / Dundas E Royal Yo...,Etobicoke-Lakeshore,2024,Road Pothole / Road Damage,Road Operations,15,43.657597,-79.516662
2374,Highway 404 / Steeles Av E 404 S Ramp,Don Valley North,2026,Road Pothole / Road Damage,Road Operations,14,43.810279,-79.347627
874,Gardiner X W Gardiner C W / Gardiner XWY,Etobicoke-Lakeshore,2023,Road Pothole / Road Damage,Road Operations,14,43.620141,-79.515076
93,Avenue Rd / 401 C W Avenue Rd Ramp,York Centre,2026,Road Pothole / Road Damage,Road Operations,14,43.743220,-79.424222
764,Gardiner Lakeshore E / Gardiner E Lower Jarvis...,Spadina-Fort York,2024,Clean Up Debris On Road,Road Operations,13,43.645324,-79.371020
3468,Robertson Cres / Queens Quay W,Spadina-Fort York,2023,Traffic Signal Repair,TMC,13,43.639029,-79.385463
792,Gardiner Lakeshore E / Gardiner E Lower Jarvis...,Spadina-Fort York,2026,Road Pothole / Road Damage,Road Operations,13,43.645324,-79.371020
2577,Humber River Recreational Trl / Humber River,Etobicoke Centre,2020,Traffic Signal Repair,TMC,13,43.723644,-79.540723
2218,Highway 401 / Warden Ave,Scarborough-Agincourt,2026,Road Pothole / Road Damage,Road Operations,13,43.770475,-79.304113
2829,Lake Shore Blvd W / Gardiner Jameson Av Ramp,Parkdale-High Park,2025,Clean Up Debris On Road,Road Operations,12,43.633468,-79.436362
736,Gardiner Lakeshore E / Gardiner E Lower Jarvis...,Spadina-Fort York,2021,Road Pothole / Road Damage,Road Operations,12,43.645324,-79.371020
3458,Robertson Cres / Queens Quay W,Spadina-Fort York,2022,Traffic Signal Repair,TMC,11,43.639029,-79.385463
3984,Wilket Creek Trl / West Don River Trl,Don Valley West,2025,Tree Emergency Clean Up,Forestry Operations,11,43.717353,-79.352292
4065,York St / Queens Quay W,Spadina-Fort York,2022,Traffic Signal Repair,TMC,11,43.640028,-79.380037
3827,Steeles Ave W / Martin Grove Rd / C N R,Etobicoke North,2026,Road Pothole / Road Damage,Road Operations,11,43.757865,-79.603400
1619,Highway 401 / Allen S 401 C E Ramp,Eglinton-Lawrence,2026,Road Pothole / Road Damage,Road Operations,11,43.731803,-79.440133
3527,Royal York S Dundas E Ramp / Dundas E Royal Yo...,Etobicoke-Lakeshore,2022,Pick Up Dead Wildlife,Toronto Animal Services,11,43.657597,-79.516662
3983,Wilket Creek Trl / West Don River Trl,Don Valley West,2025,Tree Emergency Clean Up,Forestry & Recreation,11,43.717353,-79.352292
1414,Harbour St / Lake Shore Blvd W,Spadina-Fort York,2025,Contractor Complaint,Road Operations,10,43.640609,-79.382574
2295,Highway 401 / Yonge St,Eglinton-Lawrence,2022,Road Pothole / Road Damage,Road Operations,10,43.753616,-79.408389
2239,Highway 401 / Weston Rd,York South-Weston,2021,Traffic Signal Repair,TMC,10,43.713051,-79.536053
741,Gardiner Lakeshore E / Gardiner E Lower Jarvis...,Spadina-Fort York,2022,Clean Up Debris On Road,Road Operations,10,43.645324,-79.371020
1954,Highway 401 / Leslie St,Don Valley West,2026,Road Pothole / Road Damage,Road Operations,10,43.766524,-79.363071
2664,Huntingwood Dr / East Highland Creek Trl,Scarborough-Agincourt,2020,Road Pothole / Road Damage,Road Operations,10,43.796945,-79.284029
725,Gardiner Lakeshore E / Gardiner E Lower Jarvis...,Spadina-Fort York,2020,Road Pothole / Road Damage,Road Operations,10,43.645324,-79.371020
3740,Spadina Ave / Spadina Cres,University-Rosedale,2024,Traffic Signal Repair,TMC,10,43.660368,-79.401029
153,Bayview Ave / 401 C E Bayview Ramp,Don Valley West,2023,Road Pothole / Road Damage,Road Operations,10,43.761843,-79.386845
834,Gardiner W Spadina Ramp / Gardiner Lakeshore W...,Spadina-Fort York,2024,Clean Up Illegal Dumping On City Road Allowance,Collections,10,43.639313,-79.389784
1841,Highway 401 / Kennedy Rd,Scarborough Centre,2023,Road Pothole / Road Damage,Road Operations,10,43.774845,-79.284545
4090,York St / Queens Quay W,Spadina-Fort York,2024,Traffic Signal Repair,TMC,10,43.640028,-79.380037
3887,Weston Rd / Black Creek,York South-Weston,2020,Road Pothole / Road Damage,Road Operations,9,43.683317,-79.479993
1288,Gardiner XWY / Spadina Ave,Spadina-Fort York,2026,Road Pothole / Road Damage,Road Operations,9,43.638739,-79.392314
2575,Humber River Recreational Trl / Humber River,Etobicoke Centre,2020,Road Pothole / Road Damage,Road Operations,9,43.723644,-79.540723
3902,Weston Rd / Black Creek,York South-Weston,2022,Road Pothole / Road Damage,Road Operations,9,43.683317,-79.479993
2883,Lawrence Ave E / The Donway E,Don Valley East,2025,Traffic Signal Repair,TMC,9,43.737696,-79.340978
2371,Highway 404 / Steeles Av E 404 S Ramp,Don Valley North,2025,Road Pothole / Road Damage,Road Operations,9,43.810279,-79.347627
2589,Humber River Recreational Trl / Humber River,Etobicoke Centre,2021,Traffic Signal Repair,TMC,9,43.723644,-79.540723
2685,Huntingwood Dr / East Highland Creek Trl,Scarborough-Agincourt,2023,Traffic Signal Repair,TMC,9,43.796945,-79.284029
2969,Leslie St / Old Cummer Ave,Don Valley North,2024,Pick Up Dead Wildlife,Toronto Animal Services,9,43.793968,-79.368928

In [ ]:
direct_matches_group.sort_values('yearly_requests',ascending=False).head(50)

,INTERSECTION_DESC,ward,year,service_request_type,section,yearly_requests,Latitude,Longitude
58660,Humber River Recreational Trl,Etobicoke Centre,2023,Injured Wildlife,Toronto Animal Services,332,43.743767,-79.555718
58659,Humber River Recreational Trl,Etobicoke Centre,2022,Damaged Concrete Sidewalk,Road Operations,166,43.743767,-79.555718
58664,Humber River Recreational Trl,Parkdale-High Park,2024,Tree Emergency Clean Up,Forestry & Recreation,166,43.743767,-79.555718
58663,Humber River Recreational Trl,Etobicoke-Lakeshore,2023,General Tree Maintenance,Forestry Operations,166,43.743767,-79.555718
58666,Humber River Recreational Trl,Parkdale-High Park,2025,Injured Wildlife,Toronto Animal Services,166,43.743767,-79.555718
58662,Humber River Recreational Trl,Etobicoke Centre,2025,Clean Up Debris On Road,Road Operations,166,43.743767,-79.555718
58667,Humber River Recreational Trl,Parkdale-High Park,2025,Tree Emergency Clean Up,Forestry & Recreation,166,43.743767,-79.555718
58661,Humber River Recreational Trl,Etobicoke Centre,2023,Park Use,Parks Enforcement,166,43.743767,-79.555718
58668,Humber River Recreational Trl,Parkdale-High Park,2025,Tree Emergency Clean Up,Forestry Operations,166,43.743767,-79.555718
58665,Humber River Recreational Trl,Parkdale-High Park,2024,Tree Emergency Clean Up,Forestry Operations,166,43.743767,-79.555718
116823,Steeles Ave W,Etobicoke North,2024,Road Pothole / Road Damage,Road Operations,120,43.794018,-79.438384
112114,Spadina Ave / Queen St W,Spadina-Fort York,2022,Amplified or Musical Instrument Noise,Bylaw Enforcement,111,43.648742,-79.396371
116825,Steeles Ave W,Etobicoke North,2025,Road Pothole / Road Damage,Road Operations,105,43.794018,-79.438384
11971,Beltline Trl,Eglinton-Lawrence,2024,Park Use,Parks Enforcement,93,43.699617,-79.410231
116819,Steeles Ave W,Etobicoke North,2022,Road Pothole / Road Damage,Road Operations,75,43.794018,-79.438384
81864,Martin Goodman Trl,Beaches-East York,2023,Park Use,Parks Enforcement,73,43.636937,-79.447431
81865,Martin Goodman Trl,Parkdale-High Park,2022,Clean Up Illegal Dumping On Roadways And Bridg...,Waste Enforcement,73,43.636937,-79.447431
81866,Martin Goodman Trl,Toronto-Danforth,2022,Injured Wildlife,Toronto Animal Services,73,43.636937,-79.447431
72297,Lake Shore Blvd W,Etobicoke-Lakeshore,2022,Traffic Signal Repair,TMC,72,43.637049,-79.397993
119237,Taylor Creek Trl,Beaches-East York,2021,Injured Wildlife,Toronto Animal Services,64,43.701334,-79.331664
72296,Lake Shore Blvd W,Etobicoke-Lakeshore,2022,Road Pothole / Road Damage,Road Operations,60,43.637049,-79.397993
31864,David A Balfour Park Trl,Toronto-St. Paul's,2024,Litter / Bin / Overflow Or Not Picked Up,Collections,56,43.691301,-79.390919
93431,Pape Ave / Danforth Ave,Toronto-Danforth,2021,Traffic Signal Repair,TMC,51,43.678929,-79.344875
58562,Humber Bay Park East Trl,Etobicoke-Lakeshore,2023,Pick Up Dead Wildlife,Toronto Animal Services,48,43.622366,-79.479801
58563,Humber Bay Park East Trl,Etobicoke-Lakeshore,2025,Injured Wildlife,Toronto Animal Services,48,43.622366,-79.479801
64869,Keele St / Steeles Ave W,York Centre,2026,Road Pothole / Road Damage,Road Operations,46,43.781542,-79.494499
83812,McCowan Rd / Sheppard Ave E,Scarborough North,2025,Road Pothole / Road Damage,Road Operations,46,43.789620,-79.258839
74798,Lawrence Ave E / Bayview Ave,Don Valley West,2026,Road Pothole / Road Damage,Road Operations,44,43.727528,-79.381890
9987,Bayview Ave / Corktown Common Trl,Toronto Centre,2024,Park Use,Parks Enforcement,42,43.653751,-79.353749
74776,Lawrence Ave E / Bayview Ave,Don Valley West,2024,Road Pothole / Road Damage,Road Operations,42,43.727528,-79.381890
101762,Richmond St E / Berkeley St,Toronto Centre,2025,Pick Up Dead Wildlife,Toronto Animal Services,41,43.654266,-79.365297
55028,Guildwood Park Trl,Scarborough-Guildwood,2025,Tree Emergency Clean Up,Forestry Operations,41,43.745709,-79.192971
55027,Guildwood Park Trl,Scarborough-Guildwood,2025,Tree Emergency Clean Up,Forestry & Recreation,41,43.745709,-79.192971
74744,Lawrence Ave E / Bayview Ave,Don Valley West,2022,Road Pothole / Road Damage,Road Operations,40,43.727528,-79.381890
125308,Warden Ave / Comstock Rd,Scarborough Southwest,2025,Traffic Signal Repair,TMC,40,43.721532,-79.284993
70764,Kipling Ave / Kipling Ave Bicycle Trl,Etobicoke North,2026,Road Pothole / Road Damage,Road Operations,39,43.753541,-79.587062
40794,East Don River Trl,Don Valley North,2023,Park Use,Parks Enforcement,38,43.797009,-79.381656
74757,Lawrence Ave E / Bayview Ave,Don Valley West,2023,Road Pothole / Road Damage,Road Operations,38,43.727528,-79.381890
132847,Yonge St / Dundas Sq,Toronto Centre,2022,Amplified or Musical Instrument Noise,Bylaw Enforcement,38,43.655713,-79.380651
73637,Lake Shore Blvd W / Windermere Ave,Parkdale-High Park,2022,Road Pothole / Road Damage,Road Operations,38,43.634958,-79.467960
80924,Markham Rd / Lawrence Ave E,Scarborough-Guildwood,2025,Traffic Signal Repair,TMC,37,43.759823,-79.225324
58574,Humber Bay Shores Park Trl,Etobicoke-Lakeshore,2024,Pick Up Dead Domestic Animal,Toronto Animal Services,36,43.624210,-79.477272
58575,Humber Bay Shores Park Trl,Etobicoke-Lakeshore,2025,Park Use,Parks Enforcement,36,43.624210,-79.477272
107966,Sewells Rd / Old Finch Ave,Scarborough-Rouge Park,2026,Road Pothole / Road Damage,Road Operations,36,43.822891,-79.198773
72308,Lake Shore Blvd W,Etobicoke-Lakeshore,2024,Traffic Signal Repair,TMC,36,43.637049,-79.397993
38011,Dundas St W,Etobicoke-Lakeshore,2026,Road Pothole / Road Damage,Road Operations,36,43.643601,-79.533457
58573,Humber Bay Shores Park Trl,Etobicoke-Lakeshore,2023,Tree Planting,Forestry Operations,36,43.624210,-79.477272
44052,Eglinton Ave W / Weston Rd,York South-Weston,2025,Traffic Signal Repair,TMC,36,43.686994,-79.489533
72058,Lake Shore Blvd E / Leslie St,Toronto-Danforth,2020,Traffic Signal Repair,TMC,36,43.658985,-79.328301
72294,Lake Shore Blvd W,Etobicoke-Lakeshore,2022,Missing / Damaged Street Or Traffic Signs,TMC,36,43.637049,-79.397993

In [ ]:
# Print total length of matched intersections
print(f"Total Intersections: {len(intersections)}")
print(f"Total Direct Matches: {len(directmatch_gdf)}")
print(f"Total Fuzzy Matches: {len(fuzzy_matches_df)}")

In [ ]:
# Concat the matches dataframe
final_df = pd.concat([direct_matches_group, fuzzy_matches_group], ignore_index=True)

In [ ]:
# Save matched intersections as parquet
final_df.to_parquet(r'C:\Users\rahul\OneDrive\Desktop\Data Analyst\Projects\OpenData\map_files\GIS Files\smatched_intersections.parquet')

final_df.sort_values('yearly_requests',ascending=False).head(50)

,INTERSECTION_DESC,ward,year,service_request_type,section,yearly_requests,Latitude,Longitude
58660,Humber River Recreational Trl,Etobicoke Centre,2023,Injured Wildlife,Toronto Animal Services,332,43.743767,-79.555718
58666,Humber River Recreational Trl,Parkdale-High Park,2025,Injured Wildlife,Toronto Animal Services,166,43.743767,-79.555718
58667,Humber River Recreational Trl,Parkdale-High Park,2025,Tree Emergency Clean Up,Forestry & Recreation,166,43.743767,-79.555718
58661,Humber River Recreational Trl,Etobicoke Centre,2023,Park Use,Parks Enforcement,166,43.743767,-79.555718
58668,Humber River Recreational Trl,Parkdale-High Park,2025,Tree Emergency Clean Up,Forestry Operations,166,43.743767,-79.555718
58662,Humber River Recreational Trl,Etobicoke Centre,2025,Clean Up Debris On Road,Road Operations,166,43.743767,-79.555718
58659,Humber River Recreational Trl,Etobicoke Centre,2022,Damaged Concrete Sidewalk,Road Operations,166,43.743767,-79.555718
58663,Humber River Recreational Trl,Etobicoke-Lakeshore,2023,General Tree Maintenance,Forestry Operations,166,43.743767,-79.555718
58664,Humber River Recreational Trl,Parkdale-High Park,2024,Tree Emergency Clean Up,Forestry & Recreation,166,43.743767,-79.555718
58665,Humber River Recreational Trl,Parkdale-High Park,2024,Tree Emergency Clean Up,Forestry Operations,166,43.743767,-79.555718
116823,Steeles Ave W,Etobicoke North,2024,Road Pothole / Road Damage,Road Operations,120,43.794018,-79.438384
112114,Spadina Ave / Queen St W,Spadina-Fort York,2022,Amplified or Musical Instrument Noise,Bylaw Enforcement,111,43.648742,-79.396371
116825,Steeles Ave W,Etobicoke North,2025,Road Pothole / Road Damage,Road Operations,105,43.794018,-79.438384
11971,Beltline Trl,Eglinton-Lawrence,2024,Park Use,Parks Enforcement,93,43.699617,-79.410231
116819,Steeles Ave W,Etobicoke North,2022,Road Pothole / Road Damage,Road Operations,75,43.794018,-79.438384
81864,Martin Goodman Trl,Beaches-East York,2023,Park Use,Parks Enforcement,73,43.636937,-79.447431
81865,Martin Goodman Trl,Parkdale-High Park,2022,Clean Up Illegal Dumping On Roadways And Bridg...,Waste Enforcement,73,43.636937,-79.447431
81866,Martin Goodman Trl,Toronto-Danforth,2022,Injured Wildlife,Toronto Animal Services,73,43.636937,-79.447431
72297,Lake Shore Blvd W,Etobicoke-Lakeshore,2022,Traffic Signal Repair,TMC,72,43.637049,-79.397993
119237,Taylor Creek Trl,Beaches-East York,2021,Injured Wildlife,Toronto Animal Services,64,43.701334,-79.331664
72296,Lake Shore Blvd W,Etobicoke-Lakeshore,2022,Road Pothole / Road Damage,Road Operations,60,43.637049,-79.397993
31864,David A Balfour Park Trl,Toronto-St. Paul's,2024,Litter / Bin / Overflow Or Not Picked Up,Collections,56,43.691301,-79.390919
93431,Pape Ave / Danforth Ave,Toronto-Danforth,2021,Traffic Signal Repair,TMC,51,43.678929,-79.344875
58563,Humber Bay Park East Trl,Etobicoke-Lakeshore,2025,Injured Wildlife,Toronto Animal Services,48,43.622366,-79.479801
58562,Humber Bay Park East Trl,Etobicoke-Lakeshore,2023,Pick Up Dead Wildlife,Toronto Animal Services,48,43.622366,-79.479801
64869,Keele St / Steeles Ave W,York Centre,2026,Road Pothole / Road Damage,Road Operations,46,43.781542,-79.494499
83812,McCowan Rd / Sheppard Ave E,Scarborough North,2025,Road Pothole / Road Damage,Road Operations,46,43.789620,-79.258839
74798,Lawrence Ave E / Bayview Ave,Don Valley West,2026,Road Pothole / Road Damage,Road Operations,44,43.727528,-79.381890
9987,Bayview Ave / Corktown Common Trl,Toronto Centre,2024,Park Use,Parks Enforcement,42,43.653751,-79.353749
74776,Lawrence Ave E / Bayview Ave,Don Valley West,2024,Road Pothole / Road Damage,Road Operations,42,43.727528,-79.381890
55027,Guildwood Park Trl,Scarborough-Guildwood,2025,Tree Emergency Clean Up,Forestry & Recreation,41,43.745709,-79.192971
55028,Guildwood Park Trl,Scarborough-Guildwood,2025,Tree Emergency Clean Up,Forestry Operations,41,43.745709,-79.192971
101762,Richmond St E / Berkeley St,Toronto Centre,2025,Pick Up Dead Wildlife,Toronto Animal Services,41,43.654266,-79.365297
74744,Lawrence Ave E / Bayview Ave,Don Valley West,2022,Road Pothole / Road Damage,Road Operations,40,43.727528,-79.381890
125308,Warden Ave / Comstock Rd,Scarborough Southwest,2025,Traffic Signal Repair,TMC,40,43.721532,-79.284993
70764,Kipling Ave / Kipling Ave Bicycle Trl,Etobicoke North,2026,Road Pothole / Road Damage,Road Operations,39,43.753541,-79.587062
74757,Lawrence Ave E / Bayview Ave,Don Valley West,2023,Road Pothole / Road Damage,Road Operations,38,43.727528,-79.381890
73637,Lake Shore Blvd W / Windermere Ave,Parkdale-High Park,2022,Road Pothole / Road Damage,Road Operations,38,43.634958,-79.467960
132847,Yonge St / Dundas Sq,Toronto Centre,2022,Amplified or Musical Instrument Noise,Bylaw Enforcement,38,43.655713,-79.380651
40794,East Don River Trl,Don Valley North,2023,Park Use,Parks Enforcement,38,43.797009,-79.381656
80924,Markham Rd / Lawrence Ave E,Scarborough-Guildwood,2025,Traffic Signal Repair,TMC,37,43.759823,-79.225324
58575,Humber Bay Shores Park Trl,Etobicoke-Lakeshore,2025,Park Use,Parks Enforcement,36,43.624210,-79.477272
58573,Humber Bay Shores Park Trl,Etobicoke-Lakeshore,2023,Tree Planting,Forestry Operations,36,43.624210,-79.477272
72171,Lake Shore Blvd E / Lower Sherbourne St,Spadina-Fort York,2024,Contractor Complaint,Road Operations,36,43.646443,-79.366131
72308,Lake Shore Blvd W,Etobicoke-Lakeshore,2024,Traffic Signal Repair,TMC,36,43.637049,-79.397993
44052,Eglinton Ave W / Weston Rd,York South-Weston,2025,Traffic Signal Repair,TMC,36,43.686994,-79.489533
72294,Lake Shore Blvd W,Etobicoke-Lakeshore,2022,Missing / Damaged Street Or Traffic Signs,TMC,36,43.637049,-79.397993
58574,Humber Bay Shores Park Trl,Etobicoke-Lakeshore,2024,Pick Up Dead Domestic Animal,Toronto Animal Services,36,43.624210,-79.477272
38011,Dundas St W,Etobicoke-Lakeshore,2026,Road Pothole / Road Damage,Road Operations,36,43.643601,-79.533457
72058,Lake Shore Blvd E / Leslie St,Toronto-Danforth,2020,Traffic Signal Repair,TMC,36,43.658985,-79.328301

In [ ]:
final_df.groupby(['INTERSECTION_DESC', 'ward','section','service_request_type','Latitude','Longitude'])['yearly_requests'].sum().reset_index().sort_values('yearly_requests', ascending=False)

,INTERSECTION_DESC,ward,section,service_request_type,Latitude,Longitude,yearly_requests
41505,Humber River Recreational Trl,Parkdale-High Park,Forestry Operations,Tree Emergency Clean Up,43.743767,-79.555718,332
41504,Humber River Recreational Trl,Parkdale-High Park,Forestry & Recreation,Tree Emergency Clean Up,43.743767,-79.555718,332
41502,Humber River Recreational Trl,Etobicoke Centre,Toronto Animal Services,Injured Wildlife,43.743767,-79.555718,332
80904,Steeles Ave W,Etobicoke North,Road Operations,Road Pothole / Road Damage,43.794018,-79.438384,330
51898,Lawrence Ave E / Bayview Ave,Don Valley West,Road Operations,Road Pothole / Road Damage,43.727528,-79.381890,194
...,...,...,...,...,...,...,...
39042,Heath St E / Bayview Heights Dr,Don Valley West,Toronto Animal Services,Injured Wildlife,43.694994,-79.371071,1
39043,Heath St E / Bennington Heights Dr,Don Valley West,Road Operations,Road Pothole / Road Damage,43.694282,-79.374435,1
39044,Heath St E / Hudson Dr,University-Rosedale,Collections,Clean Up Litter On Laneways,43.693168,-79.379761,1
39048,Heath St E / Hudson Dr,University-Rosedale,Investigation Services,Signs,43.693168,-79.379761,1
93537,Zorra St / Caven St,Etobicoke-Lakeshore,Toronto Animal Services,Injured Wildlife,43.620265,-79.521640,1

In [ ]:
final_df['ward'].value_counts()

ward
Toronto-Danforth            8229
Etobicoke-Lakeshore         8127
Eglinton-Lawrence           7739
Parkdale-High Park          7351
Spadina-Fort York           7239
Davenport                   6890
University-Rosedale         6716
Toronto Centre              6655
Beaches-East York           6531
Toronto-St. Paul's          6455
Etobicoke Centre            6303
York South-Weston           6122
Scarborough Southwest       5810
Don Valley West             5712
Scarborough Centre          5395
York Centre                 5231
Etobicoke North             4628
Scarborough-Rouge Park      4432
Scarborough-Agincourt       3686
Scarborough-Guildwood       3661
Don Valley North            3571
Scarborough North           3340
Humber River-Black Creek    3272
Willowdale                  3248
Don Valley East             3006
Name: count, dtype: int64

In [ ]:
#top_services = pd.read_csv(r'C:\Users\rahul\OneDrive\Desktop\Data Analyst\Projects\OpenData\Dashboards\top_requests.csv')
#top_services.to_parquet(r'C:\Users\rahul\OneDrive\Desktop\Data Analyst\Projects\OpenData\Dashboards\top_requests.parquet')

In [ ]:
#top_services[top_services['service_request_type']=='General Pruning'].iloc[0]['service_request_type']

In [9]:
# Load app files and save to parquet

monthly_summary = pd.read_sql_query("SELECT * FROM monthly_distribution", engine)
service_year_summary = pd.read_sql_query("SELECT * FROM services_year_summary", engine)

monthly_summary.to_json(r'C:\Users\rahul\OneDrive\Desktop\Data Analyst\Projects\OpenData\project_dash\src\data\monthly_distribution.json', orient='records')
service_year_summary.to_json(r'C:\Users\rahul\OneDrive\Desktop\Data Analyst\Projects\OpenData\project_dash\src\data\service_year_summary.json', orient='records')

In [10]:
service_year_summary[service_year_summary['service_request_type'] == 'General Pruning']

,service_request_type,section,division,year,yearly_requests,ward,ward_id,top_month
3602,General Pruning,Climate & Forestry,Environment,2020,813,Beaches-East York,19,June
3603,General Pruning,Climate & Forestry,Environment,2020,581,Davenport,9,June
3604,General Pruning,Climate & Forestry,Environment,2020,312,Don Valley East,16,June
3605,General Pruning,Climate & Forestry,Environment,2020,328,Don Valley North,17,June
3606,General Pruning,Climate & Forestry,Environment,2020,702,Don Valley West,15,June
...,...,...,...,...,...,...,...,...
3772,General Pruning,Climate & Forestry,Environment,2026,5,Toronto Centre,13,March
3773,General Pruning,Climate & Forestry,Environment,2026,33,University-Rosedale,11,March
3774,General Pruning,Climate & Forestry,Environment,2026,17,Willowdale,18,March
3775,General Pruning,Climate & Forestry,Environment,2026,30,York Centre,6,March
3776,General Pruning,Climate & Forestry,Environment,2026,38,York South-Weston,5,March

In [37]:
monthly_summary[monthly_summary['service_request_type'] == 'Postering City Property / Structures']

,month,year,service_request_type,section,monthly_requests,yearly_requests,ytd_requests,prev_year_requests,yoy_growth,pct_contribution
439,January,2020,Postering City Property / Structures,Waste Enforcement,34,397.0,34.0,549.0,-27.69,8.56
440,February,2020,Postering City Property / Structures,Waste Enforcement,73,397.0,107.0,549.0,-27.69,18.39
441,March,2020,Postering City Property / Structures,Waste Enforcement,36,397.0,143.0,549.0,-27.69,9.07
442,May,2020,Postering City Property / Structures,Waste Enforcement,2,397.0,145.0,549.0,-27.69,0.50
443,June,2020,Postering City Property / Structures,Waste Enforcement,2,397.0,147.0,549.0,-27.69,0.50
...,...,...,...,...,...,...,...,...,...,...
6374,February,2026,Postering City Property / Structures,Waste Enforcement,55,204.0,110.0,166.0,-33.73,26.96
6375,March,2026,Postering City Property / Structures,Waste Enforcement,94,204.0,204.0,309.0,-33.98,46.08
6691,April,2021,Postering City Property / Structures,Waste Enforcement,71,733.0,239.0,397.0,84.63,9.69
6795,November,2022,Postering City Property / Structures,Waste Enforcement,151,1263.0,1214.0,733.0,72.31,11.96
6799,December,2022,Postering City Property / Structures,Waste Enforcement,49,1263.0,1263.0,733.0,72.31,3.88

In [2]:
import pandas as pd

In [2]:
top100 = pd.read_csv(r'C:\Users\rahul\OneDrive\Desktop\Data Analyst\Projects\OpenData\project_dash\src\data\top100.csv', encoding='cp1252')
top100.to_json(r'C:\Users\rahul\OneDrive\Desktop\Data Analyst\Projects\OpenData\project_dash\src\data\top100.json', orient='records')

In [3]:
top100

,service_request_type,section,total_requests,requestswiinter,% Intersections,Description,Tip,Link,Timeline
0,Zoning Regulations Violations,Investigation Services,62273,444,0.71,Report a property suspected of being used in v...,Provide as much detail as possible about the s...,https://www.toronto.ca/home/311-toronto-at-you...,Initial Response: within ~10 days (investigati...
1,Wrong Location / Time / Day,Waste Enforcement,21074,110,0.52,Report a container placed out for collection a...,The complainant's name and phone number are re...,https://www.toronto.ca/home/311-toronto-at-you...,Timeline Not Specified
2,Watermain-Possible Break,District Ops,31929,3760,11.78,"Report a suspected watermain break, such as wa...","If water is flooding a road or property, call ...",https://www.toronto.ca/home/311-toronto-at-you...,Initial Response: ~2 hours\nRepair / Action: ~...
3,Water Service Line-Turn Off/Burst,District Ops,17332,23,0.13,Report an emergency water service line burst o...,"If water is flooding your property, turn off y...",https://www.toronto.ca/city-government/account...,Initial Response: ~2 hours\nRepair / Action: d...
4,Water Service Line-No Water,District Ops,27690,31,0.11,Report a complete loss of water service at you...,Check if neighbours are also affected as a wat...,https://www.toronto.ca/home/311-toronto-at-you...,Initial Response: ~4 hours
...,...,...,...,...,...,...,...,...,...
95,Bin Investigation Request,Collections,40538,177,0.44,Request an investigation into a service issue ...,Have your civic address and bin serial number ...,https://www.toronto.ca/city-government/account...,Repair / Action: investigation within ~21 days;
96,Animal Noise,Toronto Animal Services,18440,60,0.33,Report persistent or excessive noise from an a...,Try to provide the owner's address. Without th...,https://www.toronto.ca/home/311-toronto-at-you...,Initial Response: ~5 days
97,Amplified Or Musical Instrument Noise,Bylaw Enforcement,35648,2153,6.04,Report excessive noise from amplified music or...,"Note the time, date, address, and type of nois...",https://www.toronto.ca/city-government/account...,Initial Response: ~5 days
98,Adequate Heat,Investigation Services,20182,20,0.10,Report a landlord or property owner who is fai...,Landlords must maintain a minimum indoor tempe...,https://www.toronto.ca/city-government/account...,Initial Response: 24 hours to 5 days
99,Additional Residential Organic Bin,Collections,30473,36,0.12,Request an extra green organic bin for your ho...,Additional bins may incur a fee depending on y...,https://www.toronto.ca/city-government/account...,Repair / Action: delivered within ~14 days;

In [ ]:
# Replace 0 in link column with not provided
top100.to_json(r'C:\Users\rahul\OneDrive\Desktop\Data Analyst\Projects\OpenData\project_dash\src\data\top100.json', orient='records')